### ISSUE TITLE
bugfix: секция support градиент в разных браузерах, дубль свойства

### ISSUE THREAD

**Issue by SashkaStudent** [lexanikitin/everland#70]
Проблема с отображением градиента в браузере safari:
![image](https://user-images.githubusercontent.com/40184171/185726644-b60cc495-72cf-47ee-8e03-8e61c56a0d49.png)

Дублируются свойства:

```css
.support__donations-list::after {
  background: linear-gradient(to top, #E7F0FF, transparent 70%);
  bottom: 0;
  content: '';
  height: 90%;
  left: 0;
  position: absolute;
  width: 100%;
}

@media screen and (max-width: 767px) {
  .support__donations-list::after {
    background: linear-gradient(to top, #E7F0FF, transparent 70%);
    bottom: 0;
    content: '';
    height: 80%;
    left: 0;
    position: absolute;
    width: 100%;
  }
}
```
